# Generated by Django 2.2.6 on 2019-10-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=255)),
                ('ingredient_text', models.TextField()),
                ('instruction_text', models.TextField()),
            ],
        ),
    ]
